<?php
function password_input(string $key='password'): string { $p=$_POST[$key]??''; return is_string($p)?$p:''; }
function check_password(string $p): void { valid(strlen($p)>=12 && strlen($p)<=72 && !str_contains($p,"\0"), 'Use a password between 12 and 72 bytes long without null characters. A memorable passphrase works well.'); }
function handle_accounts(string $a): bool {
    if ($a==='register') {
        rate('register:'.($_SERVER['REMOTE_ADDR']??''), 8, 900);
        $name=field('name',2,80); $email=strtolower(field('email',5,190)); $p=password_input();
        valid((bool)filter_var($email,FILTER_VALIDATE_EMAIL),'Enter a valid email address.'); check_password($p);
        valid($p===password_input('password_confirm'),'Your passwords do not match.'); valid(input('consent')==='1','Please accept the privacy notice to create an account.');
        valid(!one('SELECT id FROM students WHERE email=?',[$email]),'An account already uses this email. Try logging in.');
        db()->beginTransaction();
        try {
            $studentNumber = eligible_student_id(input('student_number'), true);
            valid(!one('SELECT account_id FROM student_id_claims WHERE student_number=?', [$studentNumber]), 'This student ID already has a personal account. Please log in.');
            query('INSERT INTO students(name,email,password_hash) VALUES (?,?,?)',[$name,$email,password_hash($p,PASSWORD_DEFAULT)]);
            $id = (int)db()->lastInsertId();
            query('INSERT INTO student_id_claims(student_number,account_id) VALUES(?,?)', [$studentNumber,$id]);
            audit('account.created',$id); db()->commit();
        } catch (Throwable $ex) {
            if (db()->inTransaction()) db()->rollBack();
            if ($ex instanceof PDOException && $ex->getCode()==='23000') throw new UserError('This email or student ID already has an account. Please log in.');
            throw $ex;
        }
        flash('Your student ID is on the approved list. Log in to get started.'); go('login');
    }
    if ($a==='login' || $a==='community-login') {
        $email=strtolower(input('email')); $ip=$_SERVER['REMOTE_ADDR']??'';
        rate('login-ip:'.$ip,30,900); rate('login-account:'.$email,8,900);
        $u=one('SELECT * FROM students WHERE email=?',[$email]);
        $hash=$u['password_hash']??'$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi.';
        valid(password_verify(password_input(),$hash) && $u!==null,'The email or password is incorrect. Please try again.');
        $community = community_account((int)$u['id']);
        $isCommunity = $community !== null;
        valid($isCommunity === ($a==='community-login'), $isCommunity ? 'Use the separate community login page for this account.' : 'Use the personal login page for this account.');
        if ($community) valid($community['status']==='approved', $community['status']==='pending' ? 'Your community request is awaiting administrator approval.' : 'Your community request was rejected. Contact the campus administrator.');
        if(password_needs_rehash($u['password_hash'],PASSWORD_DEFAULT)) query('UPDATE students SET password_hash=? WHERE id=?',[password_hash(password_input(),PASSWORD_DEFAULT),$u['id']]);
        session_regenerate_id(true); $_SESSION=['uid'=>$u['id'],'version'=>$u['session_version'],'csrf'=>bin2hex(random_bytes(32)),'last'=>time(),'born'=>time()];
        audit('account.login',(int)$u['id']); flash('Welcome back, '.explode(' ',$u['name'])[0].'.'); go('dashboard');
    }
    if ($a==='logout') { $_SESSION=[]; session_regenerate_id(true); $_SESSION['csrf']=bin2hex(random_bytes(32)); flash('You’ve been logged out. See you around campus!'); go('home'); }
    if ($a==='profile') { $u=require_user(); $name=field('name',2,80); $bio=field('bio',0,300); query('UPDATE students SET name=?,bio=? WHERE id=?',[$name,$bio,$u['id']]); flash('Your profile is up to date.'); go('profile'); }
    if ($a==='password') {
        $u=require_user(); rate('password:'.$u['id'],8,900); $current=one('SELECT password_hash FROM students WHERE id=?',[$u['id']]);
        valid(password_verify(password_input('current_password'),$current['password_hash']),'Your current password is incorrect.');
        $p=password_input('new_password'); check_password($p); valid($p===password_input('password_confirm'),'The new passwords do not match.');
        query('UPDATE students SET password_hash=?,session_version=session_version+1 WHERE id=?',[password_hash($p,PASSWORD_DEFAULT),$u['id']]);
        $_SESSION['version']=(int)scalar('SELECT session_version FROM students WHERE id=?',[$u['id']]); session_regenerate_id(true); $_SESSION['csrf']=bin2hex(random_bytes(32));
        audit('account.password_changed',(int)$u['id']); flash('Password changed. Other sessions have been signed out.'); go('profile');
    }
    if ($a==='request-organiser') { $u=require_user(); valid($u['role']==='student','You already have organiser access.'); query('UPDATE students SET organiser_requested=1 WHERE id=?',[$u['id']]); flash('Request received. A campus administrator can approve it.'); go('dashboard'); }
    if ($a==='delete-account') {
        $u=require_user(); rate('delete:'.$u['id'],5,900); valid($u['role']!=='admin','Administrator accounts cannot be deleted here.');
        $record=one('SELECT password_hash FROM students WHERE id=?',[$u['id']]); valid(password_verify(password_input('current_password'),$record['password_hash']),'Your current password is incorrect.'); valid(input('confirmation')==='DELETE','Type DELETE to confirm.');
        db()->beginTransaction(); audit('account.deleted',(int)$u['id']); query('DELETE FROM students WHERE id=?',[$u['id']]); db()->commit();
        $_SESSION=[]; session_regenerate_id(true); $_SESSION['csrf']=bin2hex(random_bytes(32)); flash('Your account and linked personal records have been deleted.'); go('home');
    }
    return false;
}
function auth_visual(string $title, string $text): void { ?><aside class="auth-visual"><div class="eyebrow">A CAMPUS FULL OF POSSIBILITIES</div><h2><?=e(str_replace('<br>',"\n",$title))?></h2><p><?=e($text)?></p><div class="auth-orbit" aria-hidden="true"><span class="orbit-word">you belong<br>here.</span><span class="orbit-sticker s1">create ✦</span><span class="orbit-sticker s2">connect ↗</span><span class="orbit-sticker s3">show up ☀</span></div><div class="auth-bottom"><?=icon('shield')?> Your people. Your privacy. Your pace.</div></aside><?php }
function login_page(): void { if(user())go('dashboard'); render_header('Welcome back'); ?><section class="auth-layout"><?php auth_visual('Good to have<br>you back.','Your next favourite moment on campus is waiting.'); ?><div class="auth-form"><div class="eyebrow">YOUR CAMPUS, CONNECTED</div><h1>Welcome back.</h1><p>Log in to your personal account.</p><p><a href="<?=e(url('community-login'))?>">Community account login</a></p><form method="post" action="<?=e(url('login'))?>"><?=action('login')?><?php text_field('Email address','email','email','','required maxlength="190" autocomplete="username"'); ?><label class="field"><span>Password</span><div class="password-wrap"><input id="login-password" type="password" name="password" required maxlength="72" autocomplete="current-password"><button type="button" data-password="login-password" aria-label="Show password">Show</button></div></label><button class="btn full">Log in <?=icon('arrow')?></button></form><p class="auth-switch">New around here? <a href="<?=e(url('register'))?>">Create an account</a></p><div class="subtle-note"><?=icon('shield')?> A private session, on your own terms.</div></div></section><?php render_footer(); }
function register_page(): void { if(user())go('dashboard'); render_header('Create your account'); ?><section class="auth-layout"><?php auth_visual('Your people.<br>Your next chapter.','A club that gets you. An event worth showing up for. It starts right here.'); ?><div class="auth-form"><div class="eyebrow">MAKE YOURSELF AT HOME</div><h1>Find your people.</h1><p>Create your free personal account, or choose a community account for your leadership team.</p><?php account_choices('personal'); ?><form method="post" action="<?=e(url('register'))?>"><?=action('register')?><?php text_field('Student ID','student_number','text','','required maxlength="40" autocomplete="off"'); text_field('Full name','name','text','','required minlength="2" maxlength="80" autocomplete="name"'); text_field('Email address','email','email','','required maxlength="190" autocomplete="email"'); ?><label class="field"><span>Password <small>12–72 bytes · try a passphrase</small></span><div class="password-wrap"><input type="password" id="new-password" name="password" required minlength="12" maxlength="72" autocomplete="new-password"><button type="button" data-password="new-password" aria-label="Show password">Show</button></div></label><?php text_field('Confirm password','password_confirm','password','','required minlength="12" maxlength="72" autocomplete="new-password"'); ?><label class="checkbox"><input type="checkbox" name="consent" value="1" required <?=input('consent')==='1'?'checked':''?>> <span>I have read the <a href="<?=e(url('privacy'))?>">privacy notice</a> and agree to respectful participation.</span></label><button class="btn full">Create my account <?=icon('arrow')?></button></form><p class="auth-switch">Already part of the campus? <a href="<?=e(url('login'))?>">Log in</a></p></div></section><?php render_footer(); }
function dashboard_page(): void {
    $u=require_user();
    $joined=rows('SELECT c.*, (SELECT COUNT(*) FROM memberships WHERE club_id=c.id) member_count FROM clubs c JOIN memberships m ON m.club_id=c.id WHERE m.student_id=? ORDER BY m.joined_at DESC',[$u['id']]);
    $upcoming=rows('SELECT e.*,c.name club_name,c.theme,c.category FROM events e JOIN clubs c ON c.id=e.club_id JOIN rsvps r ON r.event_id=e.id WHERE r.student_id=? AND e.ends_at>UTC_TIMESTAMP() ORDER BY e.starts_at',[$u['id']]);
    $owned=rows('SELECT c.*, (SELECT COUNT(*) FROM memberships WHERE club_id=c.id) member_count FROM clubs c WHERE owner_id=? ORDER BY name',[$u['id']]);
    render_header('My campus'); page_heading('YOUR LITTLE CORNER OF CAMPUS','Hey, '.explode(' ',$u['name'])[0].' 👋','A new connection, a new experience. What will you get into today?'); dashboard_nav('dashboard'); ?>
    <div class="stats-grid"><div class="stat-card"><?=icon('people')?><strong><?=count($joined)?></strong><span>Your clubs</span></div><div class="stat-card"><?=icon('calendar')?><strong><?=count($upcoming)?></strong><span>Upcoming RSVPs</span></div><div class="stat-card"><?=icon('star')?><strong><?=e(ucfirst($u['role']))?></strong><span>Your campus role</span></div></div>
    <?php if($u['role']!=='student'): ?><section class="section"><div class="section-title"><div><div class="eyebrow">MAKE THINGS HAPPEN</div><h2>Your organiser space</h2></div><a class="btn btn-small" href="<?=e(url('club-form'))?>"><?=icon('plus')?> Register a club</a></div><?php if(!$owned): empty_state('Your next community starts here.','Register your first club, then invite students and create events.'); else: ?><div class="manage-list"><?php foreach($owned as $c): ?><article class="manage-row"><div class="club-symbol <?=e($c['theme'])?>"><?=icon('people')?></div><div><h3><a href="<?=e(url('club',['id'=>$c['id']]))?>"><?=e($c['name'])?></a></h3><span class="muted"><?=$c['member_count']?> members</span></div><div class="row-actions"><a class="btn btn-ghost btn-small" href="<?=e(url('members',['id'=>$c['id']]))?>">Members</a><a class="btn btn-ghost btn-small" href="<?=e(url('club-form',['id'=>$c['id']]))?>">Edit club</a><a class="btn btn-small" href="<?=e(url('event-form',['club'=>$c['id']]))?>">Create event</a></div></article><?php endforeach; ?></div><?php endif; ?></section><?php else: ?><div class="organiser-callout"><div><h3>Bring your community together.</h3><p>Run a club? Request organiser access to create clubs and events.</p></div><?php if($u['organiser_requested']): ?><span class="pill">Request awaiting review</span><?php else: ?><form method="post"><?=action('request-organiser')?><button class="btn btn-small btn-outline">Request access <?=icon('arrow')?></button></form><?php endif; ?></div><?php endif; ?>
    <section class="section"><div class="section-title"><h2>On your calendar</h2><a class="text-link" href="<?=e(url('events'))?>">Explore events <?=icon('arrow')?></a></div><?php if(!$upcoming): empty_state('A little room for something new.','RSVP to an event and it will appear here.',url('events'),'Find an event'); else: ?><div class="event-grid"><?php foreach($upcoming as $ev)event_card($ev); ?></div><?php endif; ?></section><section class="section"><div class="section-title"><h2>Your communities</h2><a class="text-link" href="<?=e(url('clubs'))?>">Find more clubs <?=icon('arrow')?></a></div><?php if(!$joined): empty_state('There’s a place for you.','Find a club that shares your interests and make yourself at home.',url('clubs')); else: ?><div class="club-grid"><?php foreach($joined as $c)club_card($c); ?></div><?php endif; ?></section><?php render_footer();
}
function profile_page(): void { $u=require_user(); render_header('Profile & security'); page_heading('YOUR ACCOUNT','Make it yours.','Your profile, password and privacy in one place.'); dashboard_nav('profile'); ?>
    <div class="settings-grid"><section class="panel"><div class="profile-heading"><span class="avatar large"><?=e(initials($u['name']))?></span><div><h2><?=e($u['name'])?></h2><p><?=e($u['email'])?> · <?=e(ucfirst($u['role']))?></p></div></div><form method="post"><?=action('profile')?><?php text_field('Full name','name','text',$u['name'],'required minlength="2" maxlength="80"'); ?><label class="field"><span>A little about you</span><textarea name="bio" rows="3" maxlength="300"><?=old('bio',$u['bio'])?></textarea></label><button class="btn">Save profile <?=icon('check')?></button></form></section><section class="panel"><h2>A fresh password</h2><p>Changing your password signs out your other sessions.</p><form method="post"><?=action('password')?><?php text_field('Current password','current_password','password','','required autocomplete="current-password"'); text_field('New password (12–72 bytes)','new_password','password','','required minlength="12" maxlength="72" autocomplete="new-password"'); text_field('Confirm new password','password_confirm','password','','required minlength="12" maxlength="72" autocomplete="new-password"'); ?><button class="btn btn-outline">Update password <?=icon('shield')?></button></form></section></div>
    <?php if($u['role']!=='admin'): ?><section class="panel danger-zone"><h2>Leave CampusConnect</h2><p>This permanently deletes your account, memberships, RSVPs and enquiries sent while logged in. If you organise clubs, <strong>your clubs, their events and associated memberships/RSVPs will also be deleted</strong>. This cannot be undone.</p><details><summary>Delete my account</summary><form method="post" data-confirm="Permanently delete your account and all linked clubs and events? This cannot be undone."><?=action('delete-account')?><?php text_field('Current password','current_password','password','','required autocomplete="current-password"'); text_field('Type DELETE to confirm','confirmation','text','','required pattern="DELETE"'); ?><button class="btn btn-danger">Permanently delete my account</button></form></details></section><?php endif; render_footer(); }
