<?php
function handle_clubs(string $a): bool {
    if ($a==='save-club') {
        $u=organiser(); $id=(int)input('id'); if($id)owned_club($id);
        $name=field('name',3,100); $category=field('category',1,40); $tagline=field('tagline',5,150); $description=field('description',30,3000); $location=field('location',3,120); $theme=input('theme');
        valid(in_array($category,categories(),true),'Choose a valid club category.'); valid(in_array($theme,themes(),true),'Choose a valid club colour.');
        valid(!one('SELECT id FROM clubs WHERE name=? AND id<>?',[$name,$id]),'A club with this name already exists.');
        try {
            if($id) query('UPDATE clubs SET name=?,category=?,tagline=?,description=?,location=?,theme=? WHERE id=? AND owner_id=?',[$name,$category,$tagline,$description,$location,$theme,$id,$u['id']]);
            else { query('INSERT INTO clubs(name,category,tagline,description,location,theme,owner_id) VALUES(?,?,?,?,?,?,?)',[$name,$category,$tagline,$description,$location,$theme,$u['id']]); $id=(int)db()->lastInsertId(); }
        } catch(PDOException $ex) { if($ex->getCode()==='23000') throw new UserError('That club name is already in use.'); throw $ex; }
        audit('club.saved',(int)$u['id']); flash('Your club is ready to connect.'); go('club',['id'=>$id]);
    }
    if ($a==='join-club') {
        $u=require_user(); $id=(int)input('club_id'); valid((bool)one('SELECT id FROM clubs WHERE id=?',[$id]),'This club is no longer available.');
        try { query('INSERT INTO memberships(student_id,club_id) VALUES(?,?)',[$u['id'],$id]); flash('You’re part of the club. Welcome aboard!'); } catch(PDOException $ex) { if($ex->getCode()!=='23000')throw $ex; flash('You are already a member.','info'); }
        go('club',['id'=>$id]);
    }
    if ($a==='leave-club') { $u=require_user(); $id=(int)input('club_id'); query('DELETE FROM memberships WHERE student_id=? AND club_id=?',[$u['id'],$id]); flash('You have left the club. You’re welcome back anytime.'); go('club',['id'=>$id]); }
    if ($a==='remove-member') { $c=owned_club((int)input('club_id')); query('DELETE FROM memberships WHERE student_id=? AND club_id=?',[(int)input('student_id'),$c['id']]); audit('membership.removed',(int)user()['id']); flash('Membership removed.'); go('members',['id'=>$c['id']]); }
    if ($a==='delete-club') { $c=owned_club((int)input('id')); valid(input('confirmation')==='DELETE','Type DELETE to confirm club deletion.'); query('DELETE FROM clubs WHERE id=?',[$c['id']]); audit('club.deleted',(int)user()['id']); flash('Club and associated events and memberships deleted.'); go('dashboard'); }
    return false;
}
function club_card(array $c): void { ?><article class="club-card"><div class="club-card-top"><span class="club-symbol <?=e($c['theme'])?>"><?=icon($c['category']==='Technology'?'grid':($c['category']==='Creative'?'star':'people'))?></span><span class="category"><?=e($c['category'])?></span></div><h3><a href="<?=e(url('club',['id'=>$c['id']]))?>"><?=e($c['name'])?></a></h3><p><?=e($c['tagline'])?></p><div class="card-bottom"><span><?=icon('people')?> <?=(int)$c['member_count']?> members</span><a class="circle-link" aria-label="Explore <?=e($c['name'])?>" href="<?=e(url('club',['id'=>$c['id']]))?>"><?=icon('diagonal')?></a></div></article><?php }
function clubs_page(): void {
    $search=mb_substr(get('q'),0,100); $cat=get('category'); $where='1=1'; $params=[];
    if($search!=='') { $where.=' AND (c.name LIKE ? OR c.description LIKE ?)'; $params[]='%'.$search.'%'; $params[]='%'.$search.'%'; }
    if(in_array($cat,categories(),true)) { $where.=' AND c.category=?'; $params[]=$cat; }
    $clubs=rows("SELECT c.*, (SELECT COUNT(*) FROM memberships WHERE club_id=c.id) member_count FROM clubs c WHERE $where ORDER BY c.name",$params);
    render_header('Discover clubs'); page_heading('FIND YOUR KIND OF PEOPLE','Big interests. Small worlds.','From first-time makers to lifelong players. There’s a community here for you.'); ?>
    <form class="search-bar" method="get"><input type="hidden" name="page" value="clubs"><label class="search-input"><?=icon('search')?><span class="sr-only">Search clubs</span><input name="q" placeholder="What are you into?" value="<?=e($search)?>" maxlength="100"></label><label><span class="sr-only">Club category</span><select name="category"><option value="">All interests</option><?php foreach(categories() as $category): ?><option<?=selected($cat,$category)?>><?=e($category)?></option><?php endforeach; ?></select></label><button class="btn">Find my people <?=icon('arrow')?></button></form>
    <div class="filter-chips"><a class="chip <?=$cat===''?'active':''?>" href="<?=e(url('clubs',['q'=>$search]))?>">All clubs</a><?php foreach(categories() as $category): ?><a class="chip <?=$cat===$category?'active':''?>" href="<?=e(url('clubs',['q'=>$search,'category'=>$category]))?>"><?=e($category)?></a><?php endforeach; ?></div><div class="results-heading"><p><strong><?=count($clubs)?></strong> communities to explore</p><?php if($search||$cat): ?><a href="<?=e(url('clubs'))?>">Clear filters</a><?php endif; ?></div><?php if(!$clubs): empty_state('Nothing here just yet.','Try another search or explore a different interest.',url('clubs'),'See all clubs'); else: ?><div class="club-grid"><?php foreach($clubs as $c)club_card($c); ?></div><?php endif; ?>
    <section class="banner small-banner"><div><div class="eyebrow">SOMETHING MISSING?</div><h2>Build the club you wish existed.</h2><p>Meet your people by bringing them together.</p></div><a class="btn btn-light" href="<?=e(url(user()?'dashboard':'register'))?>">Become an organiser <?=icon('arrow')?></a></section><?php render_footer();
}
function club_page(): void {
    $id=(int)get('id'); $c=one('SELECT c.*,s.name owner_name,(SELECT COUNT(*) FROM memberships WHERE club_id=c.id) member_count FROM clubs c JOIN students s ON s.id=c.owner_id WHERE c.id=?',[$id]); if(!$c)fail(404,'Club not found','This community may have moved on. Explore another club.');
    $u=user(); $member=$u?(bool)one('SELECT student_id FROM memberships WHERE club_id=? AND student_id=?',[$id,$u['id']]):false; $owner=$u&&$u['id']===$c['owner_id'];
    $events=rows('SELECT e.*,c.name club_name,c.theme,c.category FROM events e JOIN clubs c ON c.id=e.club_id WHERE c.id=? AND e.ends_at>UTC_TIMESTAMP() ORDER BY e.starts_at',[$id]);
    render_header($c['name']); ?><a class="back-link" href="<?=e(url('clubs'))?>">← All communities</a><section class="detail-cover <?=e($c['theme'])?>"><span class="pill"><?=e($c['category'])?></span><span class="cover-symbol" aria-hidden="true">✳</span><div><h1><?=e($c['name'])?></h1><p><?=e($c['tagline'])?></p></div></section><div class="detail-layout"><section><div class="eyebrow">A LITTLE ABOUT US</div><h2>Your people could be here.</h2><div class="prose"><?=nl2br(e($c['description']))?></div><div class="info-pills"><span><?=icon('pin')?><?=e($c['location'])?></span><span><?=icon('people')?><?=$c['member_count']?> members</span></div><div class="section-title"><h2>Coming up at the club</h2><?php if($owner): ?><a class="text-link" href="<?=e(url('event-form',['club'=>$id]))?>">Create event <?=icon('plus')?></a><?php endif; ?></div><?php if(!$events): empty_state('Good things are in the works.','No upcoming events yet. Check back soon.'); else: ?><div class="event-grid two"><?php foreach($events as $ev)event_card($ev); ?></div><?php endif; ?></section><aside><div class="panel sticky"><div class="club-symbol <?=e($c['theme'])?>"><?=icon('people')?></div><h2><?=$member?'You’re one of us.':'Come as you are.'?></h2><p><?=$member?'You’re a member of this community. Discover its upcoming events below.':'No experience needed. Just a little curiosity and a willingness to show up.'?></p><?php if(!$u): ?><a class="btn full" href="<?=e(url('login'))?>">Log in to join <?=icon('arrow')?></a><?php else: ?><form method="post" <?=$member?'data-confirm="Leave this club? You can join again anytime."':''?>><?=action($member?'leave-club':'join-club')?><input type="hidden" name="club_id" value="<?=$id?>"><button class="btn full <?=$member?'btn-outline':''?>"><?=$member?'Leave club':'Join this community'?> <?=icon($member?'people':'plus')?></button></form><?php endif; ?><div class="subtle-note">Organised by <?=e($c['owner_name'])?></div><?php if($owner): ?><div class="stack-links"><a href="<?=e(url('club-form',['id'=>$id]))?>">Edit club</a><a href="<?=e(url('members',['id'=>$id]))?>">Manage members</a></div><?php endif; ?></div></aside></div><?php render_footer();
}
function club_form_page(): void {
    organiser(); $id=(int)get('id'); $c=$id?owned_club($id):[]; render_header($id?'Edit club':'Register a club'); page_heading('GROW YOUR COMMUNITY',$id?'A little club refresh.':'Start something together.','Make a space for the things you love.'); ?>
    <div class="editor-layout"><form class="panel" method="post"><?=action('save-club')?><input type="hidden" name="id" value="<?=$id?>"><?php text_field('Club name','name','text',$c['name']??'','required minlength="3" maxlength="100"'); text_field('One-line introduction','tagline','text',$c['tagline']??'','required minlength="5" maxlength="150"'); ?><div class="form-row"><label class="field"><span>Category</span><select name="category" required><?php foreach(categories() as $cat): ?><option<?=selected(input('category',$c['category']??''),$cat)?>><?=e($cat)?></option><?php endforeach; ?></select></label><label class="field"><span>Club colour</span><select name="theme"><?php foreach(themes() as $theme): ?><option value="<?=$theme?>"<?=selected(input('theme',$c['theme']??'mint'),$theme)?>><?=ucfirst($theme)?></option><?php endforeach; ?></select></label></div><?php textarea_field('About your community','description',$c['description']??''); text_field('Meeting place','location','text',$c['location']??'','required minlength="3" maxlength="120"'); ?><div class="row-actions"><button class="btn">Save club <?=icon('check')?></button><a class="btn btn-ghost" href="<?=e(url($id?'club':'dashboard',$id?['id'=>$id]:[]))?>">Cancel</a></div></form><aside class="panel note-panel"><div class="eyebrow">A GREAT CLUB STARTS WITH</div><h2>A reason to belong.</h2><p>Tell people what brings you together, when you meet, and what their first visit might look like.</p><p>Keep it welcoming. A newcomer should feel invited, not interviewed.</p><?=icon('star')?></aside></div>
    <?php if($id): ?><section class="panel danger-zone"><h3>Delete this club</h3><p>This permanently removes its memberships, events and RSVPs.</p><details><summary>Show deletion options</summary><form method="post" data-confirm="Delete this club and every associated event and membership?"><?=action('delete-club')?><input type="hidden" name="id" value="<?=$id?>"><?php text_field('Type DELETE','confirmation','text','','required pattern="DELETE"'); ?><button class="btn btn-danger">Delete club</button></form></details></section><?php endif; render_footer();
}
function members_page(): void { $c=owned_club((int)get('id')); $members=rows('SELECT s.id,s.name,m.joined_at FROM memberships m JOIN students s ON s.id=m.student_id WHERE m.club_id=? ORDER BY m.joined_at DESC',[$c['id']]); render_header('Club members'); page_heading('YOUR COMMUNITY',$c['name'],'Only you, as this club’s organiser, can manage its membership.'); ?><a class="back-link" href="<?=e(url('club',['id'=>$c['id']]))?>">← Back to club</a><?php if(!$members): empty_state('Your first members are on their way.','Share your club page and invite people to join.'); else: ?><div class="table-wrap panel"><table><thead><tr><th>Member</th><th>Joined</th><th>Action</th></tr></thead><tbody><?php foreach($members as $m): ?><tr><td><span class="avatar small"><?=e(initials($m['name']))?></span> <?=e($m['name'])?></td><td><?=e(when($m['joined_at'],'j M Y'))?></td><td><form method="post" data-confirm="Remove this membership?"><?=action('remove-member')?><input type="hidden" name="club_id" value="<?=$c['id']?>"><input type="hidden" name="student_id" value="<?=$m['id']?>"><button class="text-button danger-text">Remove</button></form></td></tr><?php endforeach; ?></tbody></table></div><?php endif; render_footer(); }
