<?php
function event_record(int $id): ?array { return one('SELECT e.*,c.name club_name,c.theme,c.category,c.owner_id,(SELECT COUNT(*) FROM rsvps WHERE event_id=e.id) attendee_count FROM events e JOIN clubs c ON c.id=e.club_id WHERE e.id=?',[$id]); }
function owned_event(int $id): array { $u=organiser(); $ev=event_record($id); if(!$ev||$ev['owner_id']!==$u['id'])fail(404,'Event not found','This event does not exist or you do not manage it.'); return $ev; }
function parse_event_date(string $key): string {
    $raw=input($key); $date=DateTimeImmutable::createFromFormat('!Y-m-d\TH:i',$raw); valid($date!==false && $date->format('Y-m-d\TH:i')===$raw,'Enter a valid event date and time.'); return $date->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');
}
function handle_events(string $a): bool {
    if($a==='save-event') {
        organiser(); $id=(int)input('id'); if($id)owned_event($id); $club=owned_club((int)input('club_id'));
        $title=field('title',3,120); $description=field('description',20,4000); $location=field('location',3,150); $starts=parse_event_date('starts_at'); $ends=parse_event_date('ends_at');
        valid($ends>$starts,'The event must end after it starts.'); valid($ends>gmdate('Y-m-d H:i:s'),'The event must end in the future.');
        $capacity=filter_var(input('capacity'),FILTER_VALIDATE_INT); valid($capacity!==false && $capacity>=1 && $capacity<=10000,'Capacity must be between 1 and 10,000.');
        db()->beginTransaction();
        try {
            if($id) { query('SELECT id FROM events WHERE id=? FOR UPDATE',[$id]); valid($capacity>=(int)scalar('SELECT COUNT(*) FROM rsvps WHERE event_id=?',[$id]),'Capacity cannot be smaller than the current RSVP count.'); query('UPDATE events SET club_id=?,title=?,description=?,starts_at=?,ends_at=?,location=?,capacity=? WHERE id=?',[$club['id'],$title,$description,$starts,$ends,$location,$capacity,$id]); }
            else { query('INSERT INTO events(club_id,title,description,starts_at,ends_at,location,capacity) VALUES(?,?,?,?,?,?,?)',[$club['id'],$title,$description,$starts,$ends,$location,$capacity]); $id=(int)db()->lastInsertId(); }
            db()->commit();
        } catch(Throwable $ex) { if(db()->inTransaction())db()->rollBack(); throw $ex; }
        audit('event.saved',(int)user()['id']); flash('Your event is ready. Let’s make it a good one.'); go('event',['id'=>$id]);
    }
    if($a==='rsvp') {
        $u=require_user(); $id=(int)input('event_id'); db()->beginTransaction();
        try {
            $ev=one('SELECT * FROM events WHERE id=? FOR UPDATE',[$id]); valid((bool)$ev,'This event is no longer available.'); valid($ev['starts_at']>gmdate('Y-m-d H:i:s'),'RSVPs close when the event begins.');
            valid(!one('SELECT student_id FROM rsvps WHERE event_id=? AND student_id=?',[$id,$u['id']]),'You already have a place at this event.');
            valid((int)scalar('SELECT COUNT(*) FROM rsvps WHERE event_id=?',[$id])<(int)$ev['capacity'],'This event is full. Check back in case a spot opens up.');
            query('INSERT INTO rsvps(student_id,event_id) VALUES(?,?)',[$u['id'],$id]); db()->commit();
        } catch(Throwable $ex) { if(db()->inTransaction())db()->rollBack(); throw $ex; }
        flash('You’re on the list! Your event is in My campus.'); go('event',['id'=>$id]);
    }
    if($a==='cancel-rsvp') { $u=require_user(); $id=(int)input('event_id'); query('DELETE FROM rsvps WHERE student_id=? AND event_id=?',[$u['id'],$id]); flash('Your RSVP has been cancelled.'); go('event',['id'=>$id]); }
    if($a==='delete-event') { $ev=owned_event((int)input('id')); valid(input('confirmation')==='DELETE','Type DELETE to confirm event deletion.'); query('DELETE FROM events WHERE id=?',[$ev['id']]); audit('event.deleted',(int)user()['id']); flash('Event and associated RSVPs deleted.'); go('club',['id'=>$ev['club_id']]); }
    return false;
}
function event_card(array $ev): void { ?><article class="event-card"><a class="event-poster <?=e($ev['theme'])?>" href="<?=e(url('event',['id'=>$ev['id']]))?>" tabindex="-1" aria-hidden="true"><span class="poster-tag"><?=e($ev['category'])?></span><span class="poster-art art-<?=$ev['id']%3?>"><i></i><i></i><i></i><i></i></span><span class="poster-club"><?=e($ev['club_name'])?></span><span class="poster-arrow"><?=icon('diagonal')?></span></a><div class="event-body"><div class="event-date"><strong><?=e(when($ev['starts_at'],'d'))?></strong><span><?=e(when($ev['starts_at'],'M'))?></span></div><div><span class="event-time"><?=e(when($ev['starts_at'],'D · g:ia'))?></span><h3><a href="<?=e(url('event',['id'=>$ev['id']]))?>"><?=e($ev['title'])?></a></h3><p><?=icon('pin')?><?=e($ev['location'])?></p></div></div><div class="event-foot"><span><?=e($ev['club_name'])?></span><span class="free-tag">FREE ENTRY</span></div></article><?php }
function events_page(): void {
    $search=mb_substr(get('q'),0,100); $cat=get('category'); $period=get('period','upcoming'); if(!in_array($period,['upcoming','week','past'],true))$period='upcoming';
    $where=$period==='past'?'e.ends_at<UTC_TIMESTAMP()':'e.ends_at>=UTC_TIMESTAMP()'; $params=[];
    if($period==='week')$where.=' AND e.starts_at<DATE_ADD(UTC_TIMESTAMP(),INTERVAL 7 DAY)';
    if($search!=='') { $where.=' AND (e.title LIKE ? OR c.name LIKE ?)'; $params[]='%'.$search.'%'; $params[]='%'.$search.'%'; }
    if(in_array($cat,categories(),true)) { $where.=' AND c.category=?'; $params[]=$cat; }
    $events=rows("SELECT e.*,c.name club_name,c.theme,c.category FROM events e JOIN clubs c ON c.id=e.club_id WHERE $where ORDER BY e.starts_at " . ($period==='past'?'DESC':'ASC'),$params);
    render_header('What’s on'); page_heading('MAKE TIME FOR A GOOD TIME','Less FOMO. More memories.','Workshops, meetups and moments that make campus feel like yours.'); ?>
    <form class="search-bar" method="get"><input type="hidden" name="page" value="events"><label class="search-input"><?=icon('search')?><span class="sr-only">Search events</span><input name="q" value="<?=e($search)?>" placeholder="Find your next thing…" maxlength="100"></label><label><span class="sr-only">Category</span><select name="category"><option value="">All interests</option><?php foreach(categories() as $c): ?><option<?=selected($cat,$c)?>><?=e($c)?></option><?php endforeach; ?></select></label><label><span class="sr-only">When</span><select name="period"><option value="upcoming"<?=selected($period,'upcoming')?>>Upcoming</option><option value="week"<?=selected($period,'week')?>>Next 7 days</option><option value="past"<?=selected($period,'past')?>>Past events</option></select></label><button class="btn">Find events <?=icon('arrow')?></button></form><div class="results-heading"><p><strong><?=count($events)?></strong> reasons to show up</p><span>Times shown in <?=e($GLOBALS['config']['timezone'])?></span></div><?php if(!$events): empty_state('Your calendar has room for possibility.','No events match these filters. Try viewing all upcoming events.',url('events'),'Reset filters'); else: ?><div class="event-grid"><?php foreach($events as $ev)event_card($ev); ?></div><?php endif; render_footer();
}
function event_page(): void {
    $ev=event_record((int)get('id')); if(!$ev)fail(404,'Event not found','This event is no longer available. Explore what else is on.'); $u=user(); $attending=$u?(bool)one('SELECT student_id FROM rsvps WHERE student_id=? AND event_id=?',[$u['id'],$ev['id']]):false; $closed=$ev['starts_at']<=gmdate('Y-m-d H:i:s'); $full=$ev['attendee_count']>=$ev['capacity']; $owner=$u&&$u['id']===$ev['owner_id'];
    render_header($ev['title']); ?><a class="back-link" href="<?=e(url('events'))?>">← What’s on</a><section class="detail-cover event-cover <?=e($ev['theme'])?>"><span class="pill"><?=e($ev['category'])?> · FREE ENTRY</span><span class="cover-symbol" aria-hidden="true">✦</span><div><div class="eyebrow"><?=e($ev['club_name'])?> PRESENTS</div><h1><?=e($ev['title'])?></h1></div></section><div class="detail-layout"><section><div class="eyebrow">GOOD TIMES AHEAD</div><h2>A little more about the plan.</h2><div class="prose"><?=nl2br(e($ev['description']))?></div><a class="host-card" href="<?=e(url('club',['id'=>$ev['club_id']]))?>"><span class="club-symbol <?=e($ev['theme'])?>"><?=icon('people')?></span><div><small>YOUR HOSTS</small><h3><?=e($ev['club_name'])?></h3><span>Meet the community</span></div><?=icon('arrow')?></a><?php if($owner): ?><div class="row-actions"><a class="btn btn-outline" href="<?=e(url('event-form',['id'=>$ev['id']]))?>">Edit event</a><a class="btn btn-outline" href="<?=e(url('attendees',['id'=>$ev['id']]))?>">View RSVPs</a></div><?php endif; ?></section><aside><div class="panel sticky"><span class="pill"><?=$attending?'YOU’RE ON THE LIST':($closed?'RSVPS CLOSED':($full?'CURRENTLY FULL':'YOUR NEXT GOOD PLAN'))?></span><h2>Save your spot.</h2><div class="event-facts"><div><?=icon('calendar')?><span><strong><?=e(when($ev['starts_at'],'l, j F Y'))?></strong><?=e(when($ev['starts_at'],'g:ia'))?> – <?=e(when($ev['ends_at'],'g:ia T'))?></span></div><div><?=icon('pin')?><span><?=e($ev['location'])?></span></div><div><?=icon('people')?><span><?=$ev['attendee_count']?> going · <?=max(0,$ev['capacity']-$ev['attendee_count'])?> spots left</span></div></div><?php if($attending): ?><form method="post" data-confirm="Cancel your RSVP and release your spot?"><?=action('cancel-rsvp')?><input type="hidden" name="event_id" value="<?=$ev['id']?>"><button class="btn btn-outline full">Cancel my RSVP</button></form><?php elseif($closed||$full): ?><p class="subtle-note"><?=$closed?'This event has already started.':'All spots are taken. Check back for cancellations.'?></p><?php elseif(!$u): ?><a class="btn full" href="<?=e(url('login'))?>">Log in to RSVP <?=icon('arrow')?></a><?php else: ?><form method="post"><?=action('rsvp')?><input type="hidden" name="event_id" value="<?=$ev['id']?>"><button class="btn full">Count me in <?=icon('plus')?></button></form><?php endif; ?><a class="calendar-link" href="<?=e(url('calendar',['id'=>$ev['id']]))?>"><?=icon('calendar')?> Add to calendar (.ics)</a><p class="fine-print">Free to join. All students welcome.</p></div></aside></div><?php render_footer();
}
function event_form_page(): void {
    $u=organiser(); $id=(int)get('id'); $ev=$id?owned_event($id):[]; $clubs=rows('SELECT id,name FROM clubs WHERE owner_id=? ORDER BY name',[$u['id']]);
    render_header($id?'Edit event':'Create event'); page_heading('GIVE PEOPLE A REASON TO SHOW UP',$id?'Refine the plan.':'Make a moment happen.','Great campus memories start with a simple invitation.');
    if(!$clubs) { empty_state('First, a community. Then, a gathering.','Create a club before hosting your first event.',url('club-form'),'Register a club'); render_footer(); return; } ?>
    <div class="editor-layout"><form class="panel" method="post"><?=action('save-event')?><input type="hidden" name="id" value="<?=$id?>"><?php text_field('Event title','title','text',$ev['title']??'','required minlength="3" maxlength="120"'); ?><label class="field"><span>Hosting club</span><select name="club_id" required><?php foreach($clubs as $c): ?><option value="<?=$c['id']?>"<?=selected(input('club_id',(string)($ev['club_id']??get('club'))),(string)$c['id'])?>><?=e($c['name'])?></option><?php endforeach; ?></select></label><?php textarea_field('What should people know?','description',$ev['description']??'',4000); ?><div class="form-row"><?php text_field('Starts at','starts_at','datetime-local',isset($ev['starts_at'])?when($ev['starts_at'],'Y-m-d\TH:i'):'','required'); text_field('Ends at','ends_at','datetime-local',isset($ev['ends_at'])?when($ev['ends_at'],'Y-m-d\TH:i'):'','required'); ?></div><p class="fine-print">Dates use <?=e($GLOBALS['config']['timezone'])?> local time.</p><?php text_field('Location','location','text',$ev['location']??'','required minlength="3" maxlength="150"'); text_field('Number of spots','capacity','number',(string)($ev['capacity']??40),'required min="1" max="10000"'); ?><div class="row-actions"><button class="btn">Publish event <?=icon('arrow')?></button><a class="btn btn-ghost" href="<?=e(url($id?'event':'dashboard',$id?['id'=>$id]:[]))?>">Cancel</a></div></form><aside class="panel note-panel"><div class="eyebrow">THE ART OF A GOOD INVITATION</div><h2>Keep it clear.<br>Make it welcoming.</h2><p>Tell people what to expect, what to bring, and whether they need any experience.</p><p>Every event on CampusConnect is free to attend. Set a realistic capacity so everyone has a good time.</p><?=icon('calendar')?></aside></div><?php if($id): ?><section class="panel danger-zone"><h3>Delete event</h3><p>Its RSVP records will also be permanently removed.</p><details><summary>Show deletion options</summary><form method="post" data-confirm="Permanently delete this event and its RSVPs?"><?=action('delete-event')?><input type="hidden" name="id" value="<?=$id?>"><?php text_field('Type DELETE','confirmation','text','','required pattern="DELETE"'); ?><button class="btn btn-danger">Delete event</button></form></details></section><?php endif; render_footer();
}
function attendees_page(): void { $ev=owned_event((int)get('id')); $list=rows('SELECT s.name,r.created_at FROM rsvps r JOIN students s ON s.id=r.student_id WHERE r.event_id=? ORDER BY r.created_at',[$ev['id']]); render_header('Event RSVPs'); page_heading('YOUR GUEST LIST',$ev['title'],count($list).' students are on the list.'); ?><a class="back-link" href="<?=e(url('event',['id'=>$ev['id']]))?>">← Back to event</a><?php if(!$list): empty_state('The guest list is just getting started.','Share your event page to help people find it.'); else: ?><div class="panel table-wrap"><table><thead><tr><th>Student</th><th>RSVP received</th></tr></thead><tbody><?php foreach($list as $r): ?><tr><td><?=e($r['name'])?></td><td><?=e(when($r['created_at']))?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; render_footer(); }
function calendar_download(): never {
    $ev=event_record((int)get('id')); if(!$ev)fail(404,'Event not found','No calendar entry is available.');
    $escape=static fn($s)=>str_replace(["\\","\r","\n",';',','],["\\\\",'',"\\n",'\\;','\\,'],$s);
    $lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//CampusConnect//Events//EN','CALSCALE:GREGORIAN','BEGIN:VEVENT','UID:campusconnect-event-'.$ev['id'].'@campusconnect.local','DTSTAMP:'.gmdate('Ymd\THis\Z'),'DTSTART:'.(new DateTimeImmutable($ev['starts_at'],new DateTimeZone('UTC')))->format('Ymd\THis\Z'),'DTEND:'.(new DateTimeImmutable($ev['ends_at'],new DateTimeZone('UTC')))->format('Ymd\THis\Z'),'SUMMARY:'.$escape($ev['title']),'LOCATION:'.$escape($ev['location']),'DESCRIPTION:'.$escape($ev['description']),'END:VEVENT','END:VCALENDAR'];
    header('Content-Type: text/calendar; charset=utf-8'); header('Content-Disposition: attachment; filename="campusconnect-event-'.$ev['id'].'.ics"');
    foreach($lines as $line) { while(strlen($line)>73){ $chunk=mb_strcut($line,0,73,'UTF-8'); echo $chunk."\r\n "; $line=substr($line,strlen($chunk)); } echo $line."\r\n"; } exit;
}
