<?php
function icon(string $name, string $class = ''): string {
    $paths = [
        'arrow'=>'<path d="M5 12h14m-6-6 6 6-6 6"/>',
        'diagonal'=>'<path d="M6 18 18 6M6 6h12v12"/>',
        'search'=>'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
        'calendar'=>'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18m-14 4h3m4 0h3"/>',
        'people'=>'<circle cx="9" cy="8" r="3"/><path d="M3 21v-2a6 6 0 0 1 12 0v2m1-16a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 5"/>',
        'pin'=>'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
        'star'=>'<path d="m12 2 2.5 6.5L21 11l-6.5 2.5L12 20l-2.5-6.5L3 11l6.5-2.5Z"/>',
        'check'=>'<path d="m5 12 4 4L19 6"/>',
        'shield'=>'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',
        'mail'=>'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',
        'plus'=>'<path d="M12 5v14M5 12h14"/>',
        'clock'=>'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
        'grid'=>'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
    ];
    return '<svg class="icon ' . e($class) . '" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' . ($paths[$name] ?? $paths['star']) . '</svg>';
}
function render_header(string $title): void {
    global $page, $error;
    $u = user();
    ?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Find your people, discover student clubs and make more of campus life with CampusConnect."><meta name="theme-color" content="#123e39"><title><?=e($title)?> · CampusConnect</title><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/style.css"><script src="assets/app.js" defer></script></head><body><a class="skip-link" href="#main">Skip to content</a><div class="top-strip"><span>A little more connection. A lot more campus.</span><a href="<?=e(url('about'))?>">Made for student life <?=icon('diagonal')?></a></div><header class="site-header"><a class="brand" href="<?=e(url())?>"><span class="brand-mark">c<span>c</span></span><span>Campus<span class="brand-light">Connect</span><small>GOOD THINGS HAPPEN TOGETHER.</small></span></a><button class="menu-toggle" aria-label="Toggle navigation" aria-controls="navigation" aria-expanded="false">☰</button><nav id="navigation" aria-label="Main navigation"><a class="<?= $page==='home'?'active':'' ?>" href="<?=e(url())?>">Home</a><a class="<?=in_array($page,['clubs','club','club-form','members'])?'active':''?>" href="<?=e(url('clubs'))?>">Discover clubs</a><a class="<?=in_array($page,['events','event','event-form','attendees'])?'active':''?>" href="<?=e(url('events'))?>">What’s on</a><a class="<?=$page==='about'?'active':''?>" href="<?=e(url('about'))?>">Our story</a></nav><div class="header-actions"><?php if ($u): ?><a class="account-link" href="<?=e(url('dashboard'))?>"><span class="avatar small"><?=e(initials($u['name']))?></span><span>My campus</span></a><form method="post" action="<?=e(url('home'))?>"><?=action('logout')?><button class="text-button" type="submit">Log out</button></form><?php else: ?><a class="login-link" href="<?=e(url('login'))?>">Log in</a><a class="btn btn-small" href="<?=e(url('register'))?>">Join the campus <?=icon('arrow')?></a><?php endif; ?></div></header><main id="main" class="container">
    <?php foreach ($_SESSION['flash']??[] as [$message,$kind]): ?><div class="notice <?=e($kind)?>" role="status"><?=icon('check')?><span><?=e($message)?></span><button type="button" data-dismiss aria-label="Dismiss message">×</button></div><?php endforeach; unset($_SESSION['flash']); if ($error): ?><div class="notice error" role="alert"><?=icon('shield')?><span><?=e($error)?></span></div><?php endif;
}
function render_footer(): void { ?>
    </main><footer class="footer"><div class="footer-top"><a class="brand" href="<?=e(url())?>"><span class="brand-mark">c<span>c</span></span><span>CampusConnect<small>YOUR NEXT CHAPTER STARTS HERE.</small></span></a><p>Less scrolling. More showing up.<br>Find your kind of campus life.</p><div><a href="<?=e(url('clubs'))?>">Find a club</a><a href="<?=e(url('events'))?>">Find an event</a></div><div><a href="<?=e(url('help'))?>">Help &amp; getting started</a><a href="<?=e(url('contact'))?>">Get in touch</a><a href="<?=e(url('privacy'))?>">Privacy & your data</a></div></div><div class="footer-bottom"><span>© <?=date('Y')?> CampusConnect · A student community project</span><span>Built for belonging. <?=icon('star')?></span></div></footer></body></html><?php }
function page_heading(string $eyebrow, string $title, string $description, string $extra=''): void { ?><section class="page-heading"><div><div class="eyebrow"><?=e($eyebrow)?></div><h1><?=e($title)?></h1><p><?=e($description)?></p></div><?=$extra?></section><?php }
function empty_state(string $title, string $description, string $link='', string $label='Explore clubs'): void { ?><div class="empty panel"><?=icon('star')?><h3><?=e($title)?></h3><p><?=e($description)?></p><?php if ($link): ?><a class="btn btn-small" href="<?=e($link)?>"><?=e($label)?> <?=icon('arrow')?></a><?php endif; ?></div><?php }
function dashboard_nav(string $active): void { ?><nav class="tabs" aria-label="Account navigation"><a class="<?=$active==='dashboard'?'active':''?>" href="<?=e(url('dashboard'))?>"><?=icon('grid')?> My dashboard</a><a class="<?=$active==='profile'?'active':''?>" href="<?=e(url('profile'))?>">Profile & security</a><?php if(community_account((int)user()['id'])): ?><a class="<?=$active==='community-leaders'?'active':''?>" href="<?=e(url('community-leaders'))?>">Community leaders</a><?php endif; ?><?php if(user()['role']==='admin'): ?><a class="<?=$active==='admin'?'active':''?>" href="<?=e(url('admin'))?>">Campus administration</a><?php endif; ?></nav><?php }
function text_field(string $label, string $name, string $type='text', string $value='', string $extra=''): void { ?><label class="field"><span><?=e($label)?></span><input type="<?=e($type)?>" name="<?=e($name)?>" value="<?=$type==='password'?'':old($name,$value)?>" <?=$extra?>></label><?php }
function textarea_field(string $label, string $name, string $value='', int $max=3000): void { ?><label class="field"><span><?=e($label)?></span><textarea name="<?=e($name)?>" rows="5" maxlength="<?=$max?>" required><?=old($name,$value)?></textarea></label><?php }
